name: Pushlish Java Client to OSSRH 
on:
  workflow_dispatch:
  release:
    types: [released] 

jobs:
  test-with-coverage:
    name: Publish package 
    runs-on: ubuntu-latest
    steps:
      - name: get latest release with tag
        id: latestrelease
        run: |
          echo "::set-output name=releasetag::$(curl -s https://api.github.com/repos/lindb/client_java/releases/latest | jq '.tag_name' | sed 's/\"//g')"
      - name: confirm release tag
        run: |
          echo ${{ steps.latestrelease.outputs.releasetag }}
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          ref: ${{ steps.latestrelease.outputs.releasetag }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key pcassphrase

      - name: Publish package
        run: mvn --batch-mode deploy -Dmaven.exec.skip=true
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
